name: "Google Artifact Registry: Build and Push"

on:
  workflow_dispatch:
    inputs:
      n8n_version:
        description: "N8N version to build"
        required: false
        type: string
        default: "latest"
  push:
    branches:
      - pre-prod
  pull_request:
    branches:
      - pre-prod

env:
  NODE_OPTIONS: "--max-old-space-size=7168"
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  GAR_LOCATION: ${{ secrets.GAR_LOCATION }}
  GAR_REPOSITORY: ${{ secrets.GAR_REPOSITORY }}

jobs:
  build-docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.build.outputs.image_tag }}
      image_digest: ${{ steps.build.outputs.image_digest }}
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install pnpm
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
        with:
          version: 9

      - name: Build Docker Image
        id: build
        run: |
          # Use the build structure: "build:docker": "node scripts/build-n8n.mjs && node scripts/dockerize-n8n.mjs"
          echo "Building n8n application..."
          node scripts/build-n8n.mjs

          echo "Building Docker image..."
          export IMAGE_TAG="${{ inputs.n8n_version || 'latest' }}"
          export IMAGE_BASE_NAME="n8nio/n8n"
          node scripts/dockerize-n8n.mjs

          # Output the built image details
          echo "image_tag=${IMAGE_TAG}" >> "$GITHUB_OUTPUT"
          echo "image_digest=$(docker images --digests ${IMAGE_BASE_NAME}:${IMAGE_TAG} --format '{{.Digest}}')" >> "$GITHUB_OUTPUT"

  upload-to-gar:
    name: Upload to Google Artifact Registry
    needs: build-docker
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@f112390a2df9932162083945e46d439060d66ec2 # v2.1.4
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker to use gcloud as a credential helper
        run: |
          gcloud auth configure-docker ${{ secrets.GAR_LOCATION }}-docker.pkg.dev

      - name: Tag and Push to Google Artifact Registry
        run: |
          # Get the built image details
          LOCAL_IMAGE="n8nio/n8n:${{ needs.build-docker.outputs.image_tag }}"
          GAR_IMAGE="${{ secrets.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GAR_REPOSITORY }}/n8n:${{ needs.build-docker.outputs.image_tag }}"
          GAR_LATEST="${{ secrets.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GAR_REPOSITORY }}/n8n:latest"

          echo "Tagging local image for Google Artifact Registry..."
          docker tag $LOCAL_IMAGE $GAR_IMAGE
          docker tag $LOCAL_IMAGE $GAR_LATEST

          echo "Pushing to Google Artifact Registry..."
          docker push $GAR_IMAGE
          docker push $GAR_LATEST

          echo "=== Upload Complete ==="
          echo "Image pushed to: $GAR_IMAGE"
          echo "Latest tag: $GAR_LATEST"
